defaults:
- model
- training
- dataset: speech_dataset

dataset:
  noisy_test_dataset_dir: /Users/vtokala/Documents/Research/di_nn/Dataset/noisy_testset_1f
  noisy_training_dataset_dir: /Users/vtokala/Documents/Research/di_nn/Dataset/noisy_trainset_1f
  noisy_validation_dataset_dir: /Users/vtokala/Documents/Research/di_nn/Dataset/noisy_valset_1f
  target_test_dataset_dir: /Users/vtokala/Documents/Research/di_nn/Dataset/clean_testset_1f
  target_training_dataset_dir: /Users/vtokala/Documents/Research/di_nn/Dataset/clean_trainset_1f
  target_validation_dataset_dir: /Users/vtokala/Documents/Research/di_nn/Dataset/clean_valset_1f

model:
  attention: true
  ild_weight: 1
  ipd_weight: 10
  snr_loss_weight: 1
  stoi_weight: 10
  
training:
  accelerator: cpu
  batch_size: 20
  learning_rate: 0.0001
  n_epochs: 20
  n_workers: 4
  pin_memory: true
  strategy: ddp_spawn
  train_checkpoint_path: null
